name: PROD

on:
  push:
    # Publish `master` as Docker `latest` image.
    branches:
      - master

    # Publish `v1.2.3` tags as releases.
    tags:
      - v*

env:
  IMAGE_NAME: jwt.show

jobs:
  build_and_push_docker_image:
    name: Build and push Docker image
    runs-on: ubuntu-latest
    if: github.event_name == 'push'

    steps:
      - uses: actions/checkout@v3.0.1
        with:
          fetch-depth: 0

      - name: Build image
        run: docker build . --file Dockerfile --tag $IMAGE_NAME

      - name: Log into registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Push image
        run: |
          IMAGE_ID=ghcr.io/${{ github.repository }}/$IMAGE_NAME

          # Change all uppercase to lowercase
          IMAGE_ID=$(echo $IMAGE_ID | tr '[A-Z]' '[a-z]')

          VERSION=${{github.sha}}

          echo IMAGE_ID=$IMAGE_ID
          echo VERSION=$VERSION

          docker tag $IMAGE_NAME $IMAGE_ID:$VERSION
          docker push $IMAGE_ID:$VERSION

  commit_to_gitops:
    name: Commit to gitops
    needs: build_and_push_docker_image
    runs-on: ubuntu-latest

    steps:
      - name: Setup kustomize
        uses: imranismail/setup-kustomize@v1.6.1

      - name: Check out code
        uses: actions/checkout@v3
        with:
          repository: datamadsen/gitops
          path: gitops
          token: ${{ secrets.GH_PAT }}

      - name: Update jwt-show image with kustomize
        working-directory: gitops/jwt-show/prod
        run: |
          kustomize edit set image ghcr.io/datamadsen/jwt-show/jwt.show=ghcr.io/datamadsen/jwt-show/jwt.show:${{ github.sha }}
          cat kustomization.yaml

      - name: Commit changes
        working-directory: gitops/jwt-show/prod
        run: |
          git config --global user.email "tim@datamadsen.dk"
          git config --global user.name "jwt-show"
          git add .
          git commit -m "#prod #jwt-show ${{ github.event.head_commit.message }}"
          git push

